// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using TestTaxiFareML.Model;

namespace TestTaxiFareML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\Umkamaks\AppData\Roaming\MetaQuotes\Terminal\36A64B8C79A6163D85E6173B54096685\MQL5\Files\mt5export.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            //ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            //// Make a single prediction on the sample data and print results
            //ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            //Console.WriteLine("Using model to make single prediction -- Comparing actual CLOSE with predicted CLOSE from sample data...\n\n");
            //Console.WriteLine($"DATE: {sampleData.DATE}");
            //Console.WriteLine($"TIME: {sampleData.TIME}");
            //Console.WriteLine($"MA: {sampleData.MA}");
            //Console.WriteLine($"RSI: {sampleData.RSI}");
            //Console.WriteLine($"Volumes: {sampleData.Volumes}");
            //Console.WriteLine($"\n\nActual CLOSE: {sampleData.CLOSE} \nPredicted CLOSE: {predictionResult.Score}\n\n");
            //Console.WriteLine("=============== End of process, hit any key to finish ===============");
            //Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
