// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TestTaxiFareML.Model
{
    public class ModelInput
    {
        [ColumnName("DATE"), LoadColumn(0)]
        public float DATE { get; set; }


        [ColumnName("TIME"), LoadColumn(1)]
        public float TIME { get; set; }


        [ColumnName("CLOSE"), LoadColumn(2)]
        public float CLOSE { get; set; }


        [ColumnName("MA"), LoadColumn(3)]
        public float MA { get; set; }


        [ColumnName("RSI"), LoadColumn(4)]
        public float RSI { get; set; }


        [ColumnName("Volumes"), LoadColumn(5)]
        public float Volumes { get; set; }


    }
}
